type = "service_account"
project_id = "apartmenthunter-473102"
private_key_id = "d9dd1cdc42bc806a55a913bf3ab58cac84423c0f"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDPlhNDvT/g1W8v
QcnKDTNqhGBPLLYuDIMBJvNY2dpFqqO8g95m6Rz0j7XNj3XnQ8SnC9RX+K8ic2TP
lTdzCWEdHoAcPpHXWz9/9Wb7FStu4HBPoeOzFUDbUMOJhxoMR44OK0iBDFHi9RPh
xNT84BOg39IiL+j97VSw39r3s0HJN1HzeBeJBleOx6QHXcJRiERe4OehZWh3sUEd
HxkwKlHLVeydmpmwdWq1tG6HIuvOrUW2DINposDxC1yefym6QNjhO9ZK5Yz6kqS4
1PcMtuTPE/kz+FPm/VGnbT49ROyBSV4GjJr50K5doWRtLbeT1Ibg5czEp+Fx9Ryx
ULzyYjg5AgMBAAECggEAIakhOJPAfvG9FLmjQftAAh6zC0OhyvfGanJpdVfmF/Pi
lxf/AUr9of6HqWyA3t5TTg8SAK3XoEt75lk445N6xuECPxI6TeSC+HnPmBlHsLP+
IjuLE6f3m1iOTIe2xpT3yP5lxF8+DAJXlf132AVxyV1h0p9YNYy9dezmsdHEch8W
g+0XKnQ022oATN95I168CitKN5MFvk/exk8gwADDRXQHkMFsUAl5Qph3qMtWN0sZ
5qb7ghyCWT9gMQbET1aSrMKsD3RKw5PtwSMnkRbEY4vyYEc1+oYELyghJoPNahVJ
bHiTClGt94CnwbfkYjn5SgB8nZJsMUoMNTIxfqsM3QKBgQDtqC99oZOG+Q51FDIX
L8m3aoyF6eYWI0nYNrySh+k6VsMz4MdgbqmWfyZ0E/dAYvsTEbNulKpFnHLfGPpG
5bwvMwlq1ZWQSD9qBjqaRt869wLUjDsvhiGQWjmJ6hUBtWVVG5BKwtAvcHf5+d2x
OMi80Yl94WsyWERjzbKSu8YaNwKBgQDfm7psGMA7ML5F7zOFe8tVEaOBtgWpW3i0
OUeLU9T+u/eoEqHpH70aYmd6Hk2WZj6D1G7/wFNP/8hrAtWHpgc0NiyeVRifvO6T
M4Iu/yrn0aarSVd6Vh1Vfxun1L35o21t+sOqmf4m+JC0qVR0cTMp0RIAQgEqD36g
xQOvk5tJDwKBgBSBua9WfNtdrECwAG59wiMgf4WinCb23o1Yk8b1EUvmZquYTrvk
cJ+60v+bJW+Z2t5XXatCCrs897CGgDoT4rwT5FEiougzQ72LUg0z5lk5LTZX71d3
dHf3QRXEbBGcrGS+nyHEU6B0TPX1+IotQyz/y6RgChbrBOOzwR/mMf7bAoGBANOU
yyUVlm9rg98wo5Oeu5tXAVvvHBRQFTqTKHtRa61Ntt02JDYubgTVMAyBN/Ej9etP
y2f8V9jOsplvKRUdqJti131KD+62Gxj2GCzYDYUk/4v77eY4LbGEgGqiBtB8L0Nt
kE+RPscpU+NehidYJY1f4qSTz/44gx0kzoQIK1tJAoGBAKe1lyozPE6tkSi6+vxm
d/cmRYoTxJTMGp+E2UTg0oV2e+MdUMG61KiUZOf477TgsBmmg6KRfmpLUmq7Z1qr
4UPNNX7O+ohvUmkeoqOk0h4KJyD2+4XcnVoB1CSG1Hm8w1U2rEDGdaDVrpwa/ONX
yYZCIDmssITdenRCYo9hjvqP
-----END PRIVATE KEY-----
"""
client_email = "annawaked@apartmenthunter-473102.iam.gserviceaccount.com"
client_id = "106733621082882246324"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/annawaked%40apartmenthunter-473102.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
